coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
        only_pulls: false
comment:
  behavior: new
  require_changes: false
  hide_project_coverage: false