# fly.toml app configuration file generated for itinerary-hub on 2025-03-05T23:37:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'itinerary-hub'
primary_region = 'fra'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
