version: 2.1

executors:
  flyctl-executor:
    docker:
      - image: ubuntu:20.04
    working_directory: ~/repo

jobs:
  deploy:
    executor: flyctl-executor
    steps:
      - checkout
      - run:
          name: Install Flyctl and dependencies
          command: |
            apt-get update && apt-get install -y curl bash
            curl -sSL https://fly.io/install.sh | sh
      - run:
          name: Login to Fly.io
          command: flyctl auth login --access-token $FLY_API_TOKEN
      - run:
          name: Deploy to Fly.io
          command: flyctl deploy --app itinerary-hub

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy

