executors:
  flyctl-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  deploy:
    executor: flyctl-executor
    steps:
      - checkout
      - run:
          name: Install curl
          command: |
            apt-get update && apt-get install curl -y
      - run:
          name: Install flyctl
          command: |
            curl -sSL https://getfly.fly.dev/linux-x86-64/flyctl.tgz | tar xz
      - run:
          name: Deploy to Fly.io
          command: |
            flyctl auth login --access-token $FLY_API_TOKEN
            flyctl deploy --app itinerary-hub

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
