version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:17.0

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Grant execute permission to Gradle wrapper
          command: chmod +x ./gradlew
      - run:
          name: Set up Gradle and build
          command: ./gradlew build --no-daemon

  test:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Grant execute permission to Gradle wrapper
          command: chmod +x ./gradlew
      - run:
          name: Run Tests
          command: ./gradlew test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
