version: 2.1

executors:
  flyctl-executor:
    docker:
      - image: ubuntu:20.04
    working_directory: ~/repo

jobs:
  deploy:
    executor: flyctl-executor
    steps:
      - checkout
      - run:
          name: Install wget
          command: sudo apt-get update && sudo apt-get install -y wget
      - run:
          name: Install flyctl
          command: |
            wget -qO- 'https://getfly.fly.dev/linux-x86-64/flyctl.tgz' | tar xz
      - run:
          name: Authenticate with Fly.io
          command: ./flyctl auth login --access-token $FLY_API_TOKEN
      - run:
          name: Build Docker image
          command: |
            docker build -t registry.fly.io/$FLY_APP_NAME:$CIRCLE_BUILD_NUM .
      - run:
          name: Push Docker image to Fly.io
          command: |
            docker push registry.fly.io/$FLY_APP_NAME:$CIRCLE_BUILD_NUM
      - run:
          name: Deploy to Fly.io
          command: |
            ./flyctl deploy -i registry.fly.io/$FLY_APP_NAME:$CIRCLE_BUILD_NUM -a $FLY_APP_NAME

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
