version: 2.1
executors:
  java-executor:
    docker:
      - image: circleci/openjdk:17
  flyctl-executor:
    docker:
      - image: circleci/python:3.8
jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Set up Gradle and build
          command: ./gradlew build --no-daemon
  test:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./gradlew test
  deploy:
    executor: flyctl-executor
    steps:
      - checkout
      - run:
          name: Install flyctl
          command: |
            curl -sSL https://fly.io/install.sh | sh
      - run:
          name: Login to Fly.io
          command: flyctl auth login --access-token $FLY_API_TOKEN
      - run:
          name: Deploy to Fly.io
          command: flyctl deploy --app itinerary-hub
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: "master"
  deploy:
    jobs:
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
