version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:17-jdk

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: docker build -t your-image-name .
      - run:
          name: Save Docker image
          command: docker save your-image-name | gzip > image.tar.gz
      - persist_to_workspace:
          root: .
          paths:
            - image.tar.gz

  deploy:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Load Docker image
          command: gunzip -c /workspace/image.tar.gz | docker load
      - run:
          name: Install Flyctl
          command: |
            curl -L https://fly.io/install.sh | sh
            export PATH=$HOME/.fly/bin:$PATH
      - run:
          name: Deploy to Fly.io
          command: |
            flyctl deploy --image your-image-name --access-token "$FLY_API_TOKEN"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build