version: 2.1

executors:
  flyctl-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo

jobs:
  deploy:
    executor: flyctl-executor
    steps:
      - checkout
      - run:
          name: Install flyctl
          command: |
            wget -qO- 'https://getfly.fly.dev/linux-x86-64/flyctl.tgz' | tar xz
      - run:
          name: Deploy to Fly.io
          command: |
            ./flyctl deploy -a $FLY_APP_NAME --access-token $FLY_API_TOKEN

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy
